# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11b2fa352ae86e78a34ab96ced58ff2dd18ec580d3011bd221cb61e5714c578ea2548dc8a5dd223dd476e7d57ceeb7a4f328a8c493ae6f9053061470d91d85e6

test:
  secret_key_base: 442b98f4370174b5222c9a432836dcb4f3fbc951613a70f93f265f1019edbd6bb56f047aa32f9aa7ef9a1271e5c699d827f74d861d15b7351b0f0d3f52ccb5c9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
